// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voice.proto

package voice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Voice struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Format               string   `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Voice                []byte   `protobuf:"bytes,3,opt,name=voice,proto3" json:"voice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_196d796ed50aed6e, []int{0}
}

func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (m *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(m, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *Voice) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Voice) GetVoice() []byte {
	if m != nil {
		return m.Voice
	}
	return nil
}

func init() {
	proto.RegisterType((*Voice)(nil), "voice")
}

func init() { proto.RegisterFile("voice.proto", fileDescriptor_196d796ed50aed6e) }

var fileDescriptor_196d796ed50aed6e = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xcb, 0xcf, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe7, 0x62, 0x05, 0x73, 0x85, 0x04, 0xb8,
	0x98, 0x8b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x31, 0x2e,
	0xb6, 0xb4, 0xfc, 0xa2, 0xdc, 0xc4, 0x12, 0x09, 0x26, 0xb0, 0x20, 0x94, 0x27, 0x24, 0x02, 0xd5,
	0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe1, 0x24, 0xb1, 0x81, 0xcd, 0x33, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0x49, 0xc9, 0x6c, 0x5e, 0x00, 0x00, 0x00,
}
